# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-22 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idgo_lme_majic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermajiclme',
            name='organisation',
            field=models.ForeignKey(db_column='organisation', default=False, on_delete=django.db.models.deletion.CASCADE, related_name='organisation', to='idgo_admin.Organisation'),
        ),
        migrations.AlterField(
            model_name='usermajiclme',
            name='date_expiration_lme',
            field=models.DateField(verbose_name="Date d'expiration LME"),
        ),
        migrations.AlterField(
            model_name='usermajiclme',
            name='date_expiration_majic',
            field=models.DateField(verbose_name="Date d'expiration MAJIC"),
        ),
        migrations.AlterField(
            model_name='usermajiclme',
            name='lme',
            field=models.BooleanField(default=False, verbose_name='LME'),
        ),
        migrations.AlterField(
            model_name='usermajiclme',
            name='majic',
            field=models.BooleanField(default=False, verbose_name='MAJIC'),
        ),
    ]
