# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-13 15:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMajicLme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('majic', models.BooleanField(default=False, verbose_name='Majic')),
                ('lme', models.BooleanField(default=False, verbose_name='Majic')),
                ('date_expiration_majic', models.DateField()),
                ('date_expiration_lme', models.DateField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
